### ISSUE TITLE
Can not read metrics from dbt-core newer than 1.3

### ISSUE THREAD

**Issue by Aaron-Zhou** [cube-js/cube#6402] opened 2023-04-07 01:05 UTC
**Describe the bug**
Cube failed to read dbt-core 1.3(or newer) defined metrics. Since dbt 1.3, dbt renamed some metrics properties and this caused cude failed to read metrics from dbt.

**To Reproduce**
1. Create dbt metrics with dbt 1.3 or newer.
2. Execute dbt run
3. Add dbt.js to cude project schema.
4. Got metrics type undefined error from cube.

**Expected behavior**
dbt metrics should be loaded to cude.

**Screenshots**
Unsupported dbt metric type 'undefined'

Error: 
    at mapMetricType (/cube/node_modules/@cubejs-backend/dbt-schema-extension/src/Dbt.ts:129:11)
    at /cube/node_modules/@cubejs-backend/dbt-schema-extension/src/Dbt.ts:243:19
    at Array.map (<anonymous>)
    at /cube/node_modules/@cubejs-backend/dbt-schema-extension/src/Dbt.ts:240:43
    at Array.forEach (<anonymous>)
    at Dbt.loadMetricCubesFromNormalizedManifest (/cube/node_modules/@cubejs-backend/dbt-schema-extension/src/Dbt.ts:231:27)
    at Dbt.loadMetricCubesFromDbtProject (/cube/node_modules/@cubejs-backend/dbt-schema-extension/src/Dbt.ts:158:17)
    at dbt.js:5:3
    at DataSchemaCompiler.compileCubeFiles (/cube/node_modules/@cubejs-backend/schema-compiler/src/compiler/DataSchemaCompiler.js:155:5)
    at CompilerApi.getCompilers (/cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:56:24)
    at CompilerApi.metaConfig (/cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:188:13)
    at ApiGateway.meta (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:511:26)
    at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:316:11

**Minimally reproducible Cube Schema**

```javascript
import dbt from '@cubejs-backend/dbt-schema-extension';

asyncModule(async () => {
  // `/dbt` is the path to a folder containing `dbt-project.yml`
  await dbt.loadMetricCubesFromDbtProject('/dbts/dbt-demo');
});
```

**Version:**
[0.32.20]

**Comment by paveltiunov** [comment] 2023-04-21 22:30
Duplicate of #5599

**Closed by paveltiunov** 2023-04-21 22:30 UTC
Labels: bug
