### ISSUE TITLE
Error when use word "term" in schema

### ISSUE THREAD

**Issue by frimuchkov** [cube-js/cube#5451] opened 2022-10-10 15:52 UTC
Hi!

In some cases, when we use field Report."adTerm" in reports, Cube say thant there is no Report."ad" (!) field.

Doesn't work:
```sql
AND (Report."adTerm" LIKE '%First%' OR Report."campaign" = 'main_campaign')
```

Works fine:
```sql
AND (Report."campaign" = 'main_campaign' OR Report."adTerm" LIKE '%First%')
```

Original query:
```sql
SELECT
    'none' as "first_interval_dimension",
    MEASURE(Report.cost) as "first_interval_cost",
FROM Report
WHERE Report."date" >= '2022-09-09' AND  Report."date" <= '2022-10-06'
    AND (adTerm LIKE '%First%' OR campaign = 'main_campaign')
ORDER BY first_interval_sessions DESC NULLS LAST LIMIT 25 OFFSET 0
```

Error:
```
Internal: Error during planning: No field named 'report.ad'.
Valid fields are 'report__ad_account', 'report__ad_content', 'report__ad_platform',
'report__boost', 'report__campaign', 'report__city', 'report__country',
'report__data_source_id', 'report__date', 'report__device',
'report__domain', 'report__medium', 'report__source',
'report__source_medium', 'report__date_day', 'report__clicks'
```

As you can see, there is no `report__ad_term` in error, but we have it in our Cube and if we use adTerm before campaign everething works fine.

**Comment by frimuchkov** [comment] 2022-10-10 16:37
BTW, noticed, we don't use Report."adTerm" in in preaggregation

**Comment by gandronchik** [comment] 2022-11-03 07:34
Hi @frimuchkov. I will investigate and come back soon. Thank you 🤝

**Comment by igorlukanin** [comment] 2024-09-02 15:35
Hi @frimuchkov 👋 

I've tried to reproduce this with the following data model but wasn't able to:
```yaml
cubes:
  - name: meta_prefix
    sql: SELECT * FROM tbl WHERE (Report."adTerm" LIKE '%First%' OR Report."campaign" = 'main_campaign')

    measures:
      - name: count
        type: count
```

It works just fine:
<img width="824" alt="Screenshot 2024-09-02 at 17 34 53" src="https://github.com/user-attachments/assets/da60feae-463d-4cb1-aac6-0b9ba9f353d6">

Could you please help me reproduce this?

**Comment by igorlukanin** [comment] 2024-09-25 15:30
It looks like this has been resolved. Closing for now, please feel free to reopen if needed.

**Closed by igorlukanin** 2024-09-25 15:30 UTC
Labels: bug, api:sql
