### ISSUE TITLE
SQL API doesn't work for `select *`

### ISSUE THREAD

**Issue by iamzjk** [cube-js/cube#6940] opened 2023-07-21 19:12 UTC
SQL API doesn't work for `select *`

**Failed SQL**
```SELECT * FROM orders LIMIT 500```

**Logical Plan**
Can't find this.
Found log like
```
2023-07-21T19:02:57.190009796Z Cube SQL Error: undefined
2023-07-21T19:02:57.190034337Z --
2023-07-21T19:02:57.190036546Z "SELECT * FROM orders LIMIT 500"
2023-07-21T19:02:57.190038379Z --
2023-07-21T19:02:57.190040254Z {
2023-07-21T19:02:57.190041879Z   "apiType": "sql",
2023-07-21T19:02:57.190043629Z   "protocol": "postgres",
2023-07-21T19:02:57.190045254Z   "appName": "NULL",
2023-07-21T19:02:57.190046921Z   "sanitizedQuery": "SELECT * FROM orders LIMIT 500"
2023-07-21T19:02:57.190048629Z }
2023-07-21T19:02:57.190050254Z Error during rewrite: Can't find rewrite due to timeout reached. Please check logs for additional information.
```

**Version:**
0.33.36
in development mode

**Additional context**
I was accessing it via SQL API (Postgres)
It works if I select columns explicitly.

**Comment by iamzjk** [comment] 2023-07-21 19:51
Update: 
tested in 0.33.38, same issue.

**Comment by iamzjk** [comment] 2023-07-21 21:20
Update:
I'm able to get `select *` working by setting `CUBESQL_REWRITE_MAX_ITERATIONS=1000`, default is 300.

But the compiled query are like
```select id, name, ... from orders group by 1,2,...99```

The group is unnecessary. Is there a way I can get rid of these group by?

**Comment by igorlukanin** [comment] 2023-08-01 11:58
@iamzjk Thanks for reporting this! Could you please share which data store you use? Also, I think it would be helpful to see how your `orders` cube is defined. It contains 99 measures and dimensions, doesn't it?

**Comment by iamzjk** [comment] 2023-08-01 14:28
@igorlukanin thanks for your reply.
I use Redshift RA3.

My `orders` cube contains many dimensions. I think the `group by` is not needed, when I just do `select * from orders`

my `orders` cube look like.
```
cube(`orders`, {
  sql_table: `public.orders`,

  data_source: `default`,

  public: true,

  joins: {
    customers: {
      sql: `${CUBE}.customer_id = ${customers}.customer_id`,
      relationship: `many_to_one`,
    },
  },

  dimensions: {
    orders_uid: {
      sql: `orders_uid`,
      type: `number`,
      primary_key: true,
    },

    // ... many other dimensions
  },

  measures: {
    count: {
      type: `count`,
    }
  },

  pre_aggregations: {
    // Pre-aggregation definitions go here.
    // Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started
  },
});
```

**Comment by igorlukanin** [comment] 2023-08-01 14:31
> I think the group by is not needed, when I just do select * from orders

This is an interesting point. Cube will include the `count` measure into the result set, and all measures only make sense in the context of an aggregation, i.e., `GROUP BY`. How would you like `count` to be calculated in case of this `SELECT *` query?

Also, what is your use case? What are you trying to achieve with this `SELECT *` query?

Do you use any BI tool or other data visualization tool on top of Cube?

**Comment by iamzjk** [comment] 2023-08-01 14:43
> How would you like count to be calculated in case of this SELECT * query?
I feel `SELECT *` should only include dimensions, not measures.

> Also, what is your use case? What are you trying to achieve with this SELECT * query?
We have users often try to run `SELECT * FROM orders LIMIT 10` on tables to get an idea of what the data look like, as the tables are often very wide.

> Do you use any BI tool or other data visualization tool on top of Cube?
Yes, we use Looker, Tableau, and Power BI (from different user groups). It shouldn't be an issue with BI tools, as they don't do `SELECT *`. Only direct SQL users may try to do `SELECT *` sometimes for exploring.

**Comment by paveltiunov** [comment] 2023-08-23 06:04
Duplicate of #6750

**Closed by paveltiunov** 2023-08-23 06:04 UTC
Labels: backend:sql-api
