### ISSUE TITLE
SQL API doesn't work with dates like '1900-01-01 00:00:00 UTC'

### ISSUE THREAD

**Issue by A-Lasso** [cube-js/cube#8057] opened 2024-03-29 00:03 UTC
**Describe the bug**

Seems to be related to date value columns, not sure if I can describe it but I have many examples.

All the errors encountered:
- ERROR: Unexpected panic. Reason: called `Option::unwrap()` on a `None` value
- ERROR: Arrow error: External error: Internal error: Empty iterator passed to ScalarValue::iter_to_array. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
- ERROR: Arrow error: Compute error: TypeError: Cannot read properties of undefined (reading 'split')

### **Errors with logs and screenshots**

First error (FIXED -temporarily- but want to show this, might help)
The error:

**ERROR: Unexpected panic. Reason: called `Option::unwrap()` on a `None` value**

the same in this four tables:
- LocationTags
- LT_2024_Assessments
- LT_Annual_Meetings
- LT_Tax_Season

 Here we have a screenshot of every table with errors:
![1ACE089D77B5489B8B4188EBD96FFC5B](https://github.com/cube-js/cube/assets/125912854/86f0cc37-3140-4aef-9d37-027107e57617)
![702A611B68AF43CE908858A6EFEC0DDF](https://github.com/cube-js/cube/assets/125912854/bfa6e998-d1ff-409f-900a-dfbd8f3c146b)
![A1B997C614B64C1F96E515C39A40A339](https://github.com/cube-js/cube/assets/125912854/aa27f37c-b771-4c80-8366-59f6dc057c7b)
![8A31855891754462A72C1F71DD6DFE29](https://github.com/cube-js/cube/assets/125912854/2c37706f-974f-4afe-a4ac-7809deeefeec)

If we do a preview we can see the data in there:

![6887BBD5A70E4E4CAABF93C63820DFB2](https://github.com/cube-js/cube/assets/125912854/6e62da1d-415b-482f-b8f1-2226aef00894)
![9A78B02780694EDEB2BD157EBC914102](https://github.com/cube-js/cube/assets/125912854/00d62595-e74b-4339-961c-d0e6a82effc0)
![1A354E44819C40C4AB8B323898F9B3C3](https://github.com/cube-js/cube/assets/125912854/86948dc1-842c-49f7-be42-11640591bb74)
![181F5FA2F6E742FDA1DC392247DB4979](https://github.com/cube-js/cube/assets/125912854/37a3e01b-8e4c-45e1-bd17-9537b34762b0)

If we try to join is going to fail:
Preview:
![BF267CA615CC409AB6C10D43BCA9A70D](https://github.com/cube-js/cube/assets/125912854/e998f97a-c26f-4929-a2c3-18f1d5213724)
Question:
![DDC64065142F4BC8A6D154143256EEED](https://github.com/cube-js/cube/assets/125912854/e5d5210f-931d-4280-86e9-88dbc1c93665)

If we deselect this columns we can see the data in the tables:
- for **locationtags** is ValueAsDate column.
- for **LT_Annual_Meetings** is Asked_Board_to_Schedule and CCT_Date_Requirement columns.
- for **LT_2024_Assessments** is PostSend_Verified_HOA_Mailers_Next_Day column.
- for **LT_Tax_Season** is Upload_to_Zoho_and_send_to_board column.

We are able to run the table in the playground:

![image (29)](https://github.com/cube-js/cube/assets/125912854/979a1eb9-fab7-407b-9454-be7894971fcb)

**Solution (for this four tables case):**
The columns we needed to unselect for the table to work were all date type, so we studied our data and we have some weird dates like 0020, year 20, it can be a bad input of our clients but the thing is I don't think any date should break the table like this we filtered the LocationTags column and that fixed all tables (the other three are dynamic tables created with LocationTags values, so the date values are filtered for all four tables).

![image](https://github.com/cube-js/cube/assets/125912854/a979ee5e-43ed-4331-9e67-470db353871d)

**We filtered the dates to be  '1900-01-01 00:00:00 UTC' and after (timestamp from BigQuery, the tables that cube uses are in BigQuery), that fixed all the tables.**

See the looms I did for Metabase team:
- [IT_Bank_Reconciliation Browser Development](https://www.loom.com/share/2dca95ac9c95408a8b5d883789e78df8?sid=9013cadf-e8b3-432c-bbcb-64a23368b60d)
- [IT_Bank_Reconciliation showing errors and finding new ones](https://www.loom.com/share/ee7a42f498bb41869ebd58f1880ab679?sid=b76510da-b439-4de7-9304-e952015d7c85)
I recommend to make the videos faster.

**This same Error showed again in another question, and here is where the other errors start showing when I start doing some research/testing.** That is why this videos are from the question in the table IT_Bank_Reconciliation, that question showed same error.

I recreated the errors (in that same question of IT_Bank_Reconciliation) so I can share with you the cube logs:

- metabase shows error: **ERROR: Unexpected panic. Reason: called `Option::unwrap()` on a `None` value**
![image (6)](https://github.com/cube-js/cube/assets/125912854/3a1a1c70-4d7e-4b19-bc52-86fd0cb13a98)

(visualize)
![image (7)](https://github.com/cube-js/cube/assets/125912854/719a5a4f-781a-49df-85d3-ac9c77f2d849)

- Cube Logs:
![image (8)](https://github.com/cube-js/cube/assets/125912854/d03b98c6-39ae-40f8-9be9-14e014a7a60f)

Error during processing PostgreSQL message: CubeError: Unexpected panic. Reason: called `Option::unwrap()` on a `None` value
**apiType**
sql
**appName**
Metabase v1.48.7 
**duration**
2565
**protocol**
postgres
**query**
{
  "sql": "-- Metabase:: userID: 1 queryType: MBQL queryHash: 5906fd5f62dcb1aa1a284ef505bb5f8f5d28949189c95d251fda75c998ca44a5\nSELECT \"public\".\"IT_Bank_Reconciliation\".\"Account_Manager_Verified\" AS \"Account_Manager_Verified\", \"public\".\"IT_Bank_Reconciliation\".\"Date_Completed\" AS \"Date_Completed\", \"public\".\"IT_Bank_Reconciliation\".\"Journal_Entry_Notes\" AS \"Journal_Entry_Notes\", \"public\".\"IT_Bank_Reconciliation\".\"Notes\" AS \"Notes\", \"public\".\"IT_Bank_Reconciliation\".\"Number_of_Outstanding_Checks\" AS \"Number_of_Outstanding_Checks\", \"public\".\"IT_Bank_Reconciliation\".\"Number_of_Outstanding_Deposits\" AS \"Number_of_Outstanding_Deposits\", \"public\".\"IT_Bank_Reconciliation\".\"Uploaded_Bank_Statement\" AS \"Uploaded_Bank_Statement\", \"InteractionLocations - __cubeJoinField\".\"url\" AS \"InteractionLocations - __cubeJoinField__url\", \"MGMLocations - __cubeJoinField\".\"name\" AS \"MGMLocations - __cubeJoinField__name\", \"MGMLocations - __cubeJoinField\".\"Account_Manager\" AS \"MGMLocations - __cubeJoinField__Account_Manager\", \"MGMLocations - __cubeJoinField\".\"Active_Status\" AS \"MGMLocations - __cubeJoinField__Active_Status\", \"MGMLocations - __cubeJoinField\".\"HOA_Type\" AS \"MGMLocations - __cubeJoinField__HOA_Type\", \"MGMLocations - __cubeJoinField\".\"Plan_Type\" AS \"MGMLocations - __cubeJoinField__Plan_Type\" FROM \"public\".\"IT_Bank_Reconciliation\" LEFT JOIN \"public\".\"InteractionLocations\" AS \"InteractionLocations - __cubeJoinField\" ON \"public\".\"IT_Bank_Reconciliation\".\"__cubeJoinField\" = \"InteractionLocations - __cubeJoinField\".\"__cubeJoinField\" LEFT JOIN \"public\".\"MGMLocations\" AS \"MGMLocations - __cubeJoinField\" ON \"InteractionLocations - __cubeJoinField\".\"__cubeJoinField\" = \"MGMLocations - __cubeJoinField\".\"__cubeJoinField\" WHERE \"public\".\"IT_Bank_Reconciliation\".\"Date_Completed\" IS NOT NULL LIMIT 2000"
}

Second cube logs for the same error:
![image (9)](https://github.com/cube-js/cube/assets/125912854/d2c4b06b-23b4-4b27-8a8c-e313b73096d9)
Error during processing PostgreSQL message: CubeError: Unexpected panic. Reason: called `Option::unwrap()` on a `None` value

- metabase shows error: **ERROR: Arrow error: External error: Internal error: Empty iterator passed to ScalarValue::iter_to_array. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker**
![image (10)](https://github.com/cube-js/cube/assets/125912854/5d4af01e-b01a-4d34-8556-0be7e2e8cbd3)

- Cube Logs:
![image (11)](https://github.com/cube-js/cube/assets/125912854/4bde984c-7b11-42ef-88f2-6b86613a1714)

Error during processing PostgreSQL message: CubeError: Arrow error: External error: Internal error: Empty iterator passed to ScalarValue::iter_to_array. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker
**apiType**
sql
**appName**
Metabase v1.48.7 
**duration**
2470
**protocol**
postgres
**query**
{
  "sql": "-- Metabase:: userID: 1 queryType: MBQL queryHash: 40afdf76c37504a078858cb0fb60c64c14e52cd52a22d1c0d378fa32450f5535\nSELECT CAST(\"public\".\"IT_Bank_Reconciliation\".\"Date_Completed\" AS date) AS \"Date_Completed\", count(distinct \"public\".\"IT_Bank_Reconciliation\".\"Date_Completed\") AS \"count\" FROM \"public\".\"IT_Bank_Reconciliation\" LEFT JOIN \"public\".\"InteractionLocations\" AS \"InteractionLocations - __cubeJoinField\" ON \"public\".\"IT_Bank_Reconciliation\".\"__cubeJoinField\" = \"InteractionLocations - __cubeJoinField\".\"__cubeJoinField\" LEFT JOIN \"public\".\"MGMLocations\" AS \"MGMLocations - __cubeJoinField\" ON \"InteractionLocations - __cubeJoinField\".\"__cubeJoinField\" = \"MGMLocations - __cubeJoinField\".\"__cubeJoinField\" GROUP BY CAST(\"public\".\"IT_Bank_Reconciliation\".\"Date_Completed\" AS date) ORDER BY CAST(\"public\".\"IT_Bank_Reconciliation\".\"Date_Completed\" AS date) ASC LIMIT 10"
}

Second cube logs for the same error:
![image (12)](https://github.com/cube-js/cube/assets/125912854/828bb55f-37d7-4c67-9161-fbc36f83c8e5)

Error during processing PostgreSQL message: CubeError: Arrow error: External error: Internal error: Empty iterator passed to ScalarValue::iter_to_array. This was likely caused by a bug in DataFusion's code and we would welcome that you file an bug report in our issue tracker

- metabase shows error: **ERROR: Arrow error: Compute error: TypeError: Cannot read properties of undefined (reading 'split')**
![image (16)](https://github.com/cube-js/cube/assets/125912854/955186df-d807-46d9-bec9-b8a3e379b948)

![image (17)](https://github.com/cube-js/cube/assets/125912854/f0dff43f-8d05-4c63-a2e8-6e824ea4ff6d)

![image (18)](https://github.com/cube-js/cube/assets/125912854/07a1191b-11dc-4e58-93f7-0742a9ae0881)

![image (19)](https://github.com/cube-js/cube/assets/125912854/dbe979bc-f339-4289-bca8-09e19e06f25c)

![image (20)](https://github.com/cube-js/cube/assets/125912854/2a7332e4-b1cb-4368-8630-ca1b242ba1d3)

_I was thinking that maybe it was because I can't group by a column without a measure or another column in the group by but this example works:_
![image (13)](https://github.com/cube-js/cube/assets/125912854/638ce80e-d1cc-4607-83e4-f53376b99558)
![image (14)](https://github.com/cube-js/cube/assets/125912854/d0a94ba8-dc30-4925-a878-3490a94ae0ce)
![image (15)](https://github.com/cube-js/cube/assets/125912854/e6301a79-c30b-4e34-a202-fe82f8f5c2aa)

#### **What I understand with this testing is: the problem is in date columns in this case.**

- Cube Logs (this time we have 3 logs, will only share the logs of the first one, they all seem to say the same except with another column):
![image (21)](https://github.com/cube-js/cube/assets/125912854/cf1f56d6-4844-4024-a317-f41502975c59)

**TypeError**
TypeError: Cannot read properties of undefined (reading 'split')
    at CloudApiGateway.queryRewrite (/cube/conf/cube.js:43:47)
    at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1136:38
    at Array.map (<anonymous>)
    at CloudApiGateway.getNormalizedQueries (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1133:15)
    at CloudApiGateway.sqlApiLoad (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:1701:20)
    at /cube/node_modules/@cubejs-backend/api-gateway/src/sql-server.ts:132:13
**apiType**
sql
**appName**
Metabase v1.48.7
**duration**
213
**protocol**
postgres
**query**
{
  "measures": [],
  "dimensions": [],
  "segments": [],
  "timeDimensions": [
    {
      "dimension": "IT_Bank_Reconciliation.Date_Completed",
      "granularity": "day"
    }
  ],
  "limit": 50000
}

![image (22)](https://github.com/cube-js/cube/assets/125912854/0b255fb6-d156-4a68-b092-e09a4f787957)

Error during processing PostgreSQL message: CubeError: Arrow error: Compute error: TypeError: Cannot read properties of undefined (reading 'split')
**apiType**
sql
**appName**
Metabase v1.48.7
**duration**
588
**protocol**
postgres
**query**
{
  "sql": "-- Metabase:: userID: 1 queryType: MBQL queryHash: 84930f23b3174bcd1d90bb8cc511c6e333ecf9b119eb03de5d4004923d0b115b\nSELECT CAST(\"public\".\"IT_Bank_Reconciliation\".\"Date_Completed\" AS date) AS \"Date_Completed\" FROM \"public\".\"IT_Bank_Reconciliation\" LEFT JOIN \"public\".\"InteractionLocations\" AS \"InteractionLocations - __cubeJoinField\" ON \"public\".\"IT_Bank_Reconciliation\".\"__cubeJoinField\" = \"InteractionLocations - __cubeJoinField\".\"__cubeJoinField\" LEFT JOIN \"public\".\"MGMLocations\" AS \"MGMLocations - __cubeJoinField\" ON \"InteractionLocations - __cubeJoinField\".\"__cubeJoinField\" = \"MGMLocations - __cubeJoinField\".\"__cubeJoinField\" GROUP BY CAST(\"public\".\"IT_Bank_Reconciliation\".\"Date_Completed\" AS date) ORDER BY CAST(\"public\".\"IT_Bank_Reconciliation\".\"Date_Completed\" AS date) ASC LIMIT 2000"
}

![image (23)](https://github.com/cube-js/cube/assets/125912854/1e2a0af9-7f2d-4198-9820-71958d3c1d07)

Error during processing PostgreSQL message: CubeError: Arrow error: Compute error: TypeError: Cannot read properties of undefined (reading 'split')

#### _**I was also working in some clients dashboards and something else happened, and even the error tells me that this is from cube side:**_

![image (24)](https://github.com/cube-js/cube/assets/125912854/ec2410ba-69d1-422d-8037-2d0b1c744637)

**ERROR: Error during rewrite: Can't detect Cube query and it may be not supported yet. Please check logs for additional information. QUERY: SELECT CAST("InteractionLocations - __cubeJoinField"."createdAt" AS DATE) AS "InteractionLocations - __cubeJoinField__createdAt", SUM("public"."IT_Daily_IPS_CheckIn"."Denied") AS "sum", SUM("public"."IT_Daily_IPS_CheckIn"."Pending_Approval") AS "sum_2", SUM("public"."IT_Daily_IPS_CheckIn"."Emailed_for_Approval") AS "sum_3", SUM("public"."IT_Daily_IPS_CheckIn"."Duplicates") AS "sum_4", SUM("public"."IT_Daily_IPS_CheckIn"."Failed_Posts") AS "sum_5" FROM "public"."IT_Daily_IPS_CheckIn" LEFT JOIN "public"."InteractionLocations" AS "InteractionLocations - __cubeJoinField" ON "public"."IT_Daily_IPS_CheckIn"."__cubeJoinField" = "InteractionLocations - __cubeJoinField"."__cubeJoinField" LEFT JOIN "public"."MGMLocations" AS "MGMLocations - __cubeJoinField" ON "InteractionLocations - __cubeJoinField"."__cubeJoinField" = "MGMLocations - __cubeJoinField"."__cubeJoinField" WHERE "public"."IT_Daily_IPS_CheckIn"."Questions" IS NOT NULL GROUP BY CAST("InteractionLocations - __cubeJoinField"."createdAt" AS DATE) ORDER BY CAST("InteractionLocations - __cubeJoinField"."createdAt" AS DATE) ASC LIMIT 10**

![image (25)](https://github.com/cube-js/cube/assets/125912854/a3a3cd9b-92d4-4805-90cd-fae0dc5c4bb2)

**ERROR: Error during rewrite: Can't detect Cube query and it may be not supported yet. Please check logs for additional information. QUERY: SELECT CAST("InteractionLocations - __cubeJoinField"."createdAt" AS DATE) AS "InteractionLocations - __cubeJoinField__createdAt", SUM("public"."IT_Daily_IPS_CheckIn"."Denied") AS "sum" FROM "public"."IT_Daily_IPS_CheckIn" LEFT JOIN "public"."InteractionLocations" AS "InteractionLocations - __cubeJoinField" ON "public"."IT_Daily_IPS_CheckIn"."__cubeJoinField" = "InteractionLocations - __cubeJoinField"."__cubeJoinField" LEFT JOIN "public"."MGMLocations" AS "MGMLocations - __cubeJoinField" ON "InteractionLocations - __cubeJoinField"."__cubeJoinField" = "MGMLocations - __cubeJoinField"."__cubeJoinField" WHERE "public"."IT_Daily_IPS_CheckIn"."Questions" IS NOT NULL GROUP BY CAST("InteractionLocations - __cubeJoinField"."createdAt" AS DATE) ORDER BY CAST("InteractionLocations - __cubeJoinField"."createdAt" AS DATE) ASC LIMIT 10**

![image (26)](https://github.com/cube-js/cube/assets/125912854/41996d3d-8ae2-4df8-9752-ee8c4da52a9f)

**ERROR: Arrow error: Compute error: TypeError: Cannot read properties of undefined (reading 'split')**
Same error I showed above in this same email, and again this is a date column.

![image (27)](https://github.com/cube-js/cube/assets/125912854/efacc3c3-94b3-439b-823c-5cd5c793c84a)
(bin or unnbinned the error is still there)

The problem seems to be in the summarize/date column:
![image (28)](https://github.com/cube-js/cube/assets/125912854/aa16e08c-f1ce-4573-bc62-c42d33a2b145)

### **Version:**
Cube Cloud: stable (0.34.52) and Latest (0.35.5) -tried to see if it was fixed-

Metabase Cloud: 1.48.7

### **Additional context**

I already tested with the newer version (it didn't work) but I can't be changing the stable version, it already broke our production two different times, and we couldn't get back our metabase local production on track on the second time, so now we are on metabase cloud and re-did everything we could for our clients.
Hope you can understand that it is not so easy to test, because any change in cube would mean risk for this to happen again. 

Don't know if this has to do but all tables with IT_ and LT_ in the beginning are dynamic tables.

Really sorry if this too long but wanted to give you guys all the context I could and all the data/examples I found so this is faster or at least has more context.
Let me know if there are any more questions or something you want me to try, I think I shared all I could.
Thank you for your help and taking the time to read all this text and issues, hope we can figure out what is happening!

**Comment by igorlukanin** [comment] 2024-04-04 13:52
@A-Lasso Thanks for a very elaborate report! I've renamed the issue—do you think I've got the main idea correctly?

**Comment by A-Lasso** [comment] 2024-04-04 18:36
Yes I think so, but I'm not sure all of them have those weird dates, so I will see in playground what I can find in this other tables that cannot be filtered by date columns.

Also I was said to add the "CUBESQL_SQL_PUSH_DOWN" env variable and set it to true, but this just gave me more errors and broke even more the summarizes and tables, so I deleted it again to at least have the dashboards that were done not broken.

As you see, the IT_Bank_Reconciliation table doesn't have any data before that year:
![image](https://github.com/cube-js/cube/assets/125912854/c295adf5-af96-407b-a4a5-7e9ab38946a1)

So seems there is something else happening, if there is anything you want me to test I'll be happy to.

Also since it mentions the "split" in some errors this is what I could find with the "split" in the cube.js file.

const deconstructGlobalId = (globalId) => {
    const decoded = decodeBase64(globalId)
    const globalIdParts = decoded.split(":")

    return {
        node: globalIdParts[0],
        uuid: globalIdParts[1]
    }
}

const queryRewrite = (query, request) => {
    console.log("Rewriting for", JSON.stringify(request))
    const accountId = request.cacct !== undefined ? request.cacct : request.securityContext.cacct;

    if (query["dimensions"].length > 0) {
        var table_name = query["dimensions"][0].split(".")[0]
    }
    // measures in query
    else {
        var table_name = query["measures"][0].split(".")[0]
    }

    console.log("Using account id:", accountId);

    query.filters.push({
        member: `${table_name}.accountUuid`,
        operator: 'equals',
        values: [accountId],
    });

    return query;
}

**Comment by A-Lasso** [comment] 2024-04-05 21:25
Hello I'm here to share more examples of the problem.

![image](https://github.com/cube-js/cube/assets/125912854/581ed492-64ae-46de-988e-a3df9cc6e4d8)
![image](https://github.com/cube-js/cube/assets/125912854/61a46991-351c-44d1-835f-f481e02dbb19)

we cannot do a summarize having a not null or not empty filtering of mostly ANY column (doesn't matter if its date or not):

the visualization without a summarize:
![image](https://github.com/cube-js/cube/assets/125912854/98aeff28-5896-4fe3-91ea-ca1a92f5007c)

with a summarize:
![image](https://github.com/cube-js/cube/assets/125912854/a1be7073-52aa-4adc-8969-549120520a67)
![image](https://github.com/cube-js/cube/assets/125912854/0af5786e-d025-466d-ae60-e14f3f637897)
![image](https://github.com/cube-js/cube/assets/125912854/9c02bf26-f45f-4466-ab6b-9c16b6e61593)

**Comment by A-Lasso** [comment] 2024-04-09 23:33
Since there is still no update, I will continue to send some examples, not sure if they are repeated or not, but as I show in an older message, this doesn't look like just a date value problem.

![image](https://github.com/cube-js/cube/assets/125912854/e4160eeb-37a2-4b4d-b35d-44a3ccddad77)

I added the env variable as this logs said and this is what I got re-doing the question on metabase:

![image](https://github.com/cube-js/cube/assets/125912854/41fb753e-b7dd-440c-9e77-1d16a3aec14c)
![image](https://github.com/cube-js/cube/assets/125912854/19febbcc-4981-413c-af69-7341ed8bcf24)
![image](https://github.com/cube-js/cube/assets/125912854/e75e1805-f07a-4f96-a07f-cca87cabbb41)

Now I changed it to "Full" instead of 1 and this is what I got:
![image](https://github.com/cube-js/cube/assets/125912854/9a8c867d-b2e7-4492-8369-cb2e0a61ba18)
![image](https://github.com/cube-js/cube/assets/125912854/c43fc81f-8fe2-4e38-8223-fcbc37e7a855)
![image](https://github.com/cube-js/cube/assets/125912854/4c9ac845-8217-40cd-8815-b0b7a8c54130)

other logs (SQL Query and normal cube error log):

![image](https://github.com/cube-js/cube/assets/125912854/7b3050f8-1492-433d-a8db-14205647a6c4)

query: 
{
  "sql": "-- Metabase:: userID: 1 queryType: MBQL queryHash: 36a8c22444227518ebbf37738bfe21864c71dbe004c10a771ca5ceb64afb87e2\nSELECT \"public\".\"IT_Bank_Reconciliation\".\"interactionUuid\" AS \"interactionUuid\", \"public\".\"IT_Bank_Reconciliation\".\"accountUuid\" AS \"accountUuid\", \"public\".\"IT_Bank_Reconciliation\".\"Account_Manager_Verified\" AS \"Account_Manager_Verified\", \"public\".\"IT_Bank_Reconciliation\".\"All_Checks_Voided__Reissued\" AS \"All_Checks_Voided__Reissued\", \"public\".\"IT_Bank_Reconciliation\".\"Date_Completed\" AS \"Date_Completed\", \"public\".\"IT_Bank_Reconciliation\".\"Journal_Entry_Notes\" AS \"Journal_Entry_Notes\", \"public\".\"IT_Bank_Reconciliation\".\"Notes\" AS \"Notes\", \"public\".\"IT_Bank_Reconciliation\".\"Number_of_Outstanding_Checks\" AS \"Number_of_Outstanding_Checks\", \"public\".\"IT_Bank_Reconciliation\".\"Number_of_Outstanding_Deposits\" AS \"Number_of_Outstanding_Deposits\", \"public\".\"IT_Bank_Reconciliation\".\"TalkedConfirmed_With_Vendors\" AS \"TalkedConfirmed_With_Vendors\", \"public\".\"IT_Bank_Reconciliation\".\"Uploaded_Bank_Statement\" AS \"Uploaded_Bank_Statement\", \"public\".\"IT_Bank_Reconciliation\".\"__user\" AS \"__user\", \"public\".\"IT_Bank_Reconciliation\".\"__cubeJoinField\" AS \"__cubeJoinField\" FROM \"public\".\"IT_Bank_Reconciliation\" WHERE \"public\".\"IT_Bank_Reconciliation\".\"Account_Manager_Verified\" IS NOT NULL LIMIT 2000"
}

![image](https://github.com/cube-js/cube/assets/125912854/22910a65-8638-44a8-8569-4056f1736ecc)



Metabase question generating this error:
![image](https://github.com/cube-js/cube/assets/125912854/86b5bad8-59bf-4ffb-a3fb-6402f12a1247)
![image](https://github.com/cube-js/cube/assets/125912854/5cd05deb-bdbd-4c70-9ed8-a9ef940fddce)
![image](https://github.com/cube-js/cube/assets/125912854/e30a855b-1d75-4b03-8ba4-18fb03f9d69b)
![image](https://github.com/cube-js/cube/assets/125912854/63597a34-e264-4c27-9a59-a1f2377b1bd3)

Thank you again for the help.

**Comment by igorlukanin** [comment] 2024-04-10 14:16
@A-Lasso Thanks for the details.

> Also I was said to add the "CUBESQL_SQL_PUSH_DOWN" env variable and set it to true, but this just gave me more errors and broke even more the summarizes and tables, so I deleted it again to at least have the dashboards that were done not broken.

I would recommend to upgrade to the latest version and give this option a try again. This is going to be the default mode for the SQL API in the coming weeks/months, and I feel like making it work with Metabase is the right approach going forward.

**Comment by A-Lasso** [comment] 2024-04-15 18:21
Hello again, seems like we had code errors from our side, so I think the issue is primarily what the title says.

Sorry for all the bother and thank you so much for the help.

**Comment by HaidarZ** [comment] 2024-08-28 07:41
Please test on the latest version `cubejs/cube:v0.35.78` , it seems that the problem is fixed on this specific release.

**Comment by HaidarZ** [comment] 2024-08-28 08:05
https://github.com/cube-js/cube/pull/8583

**Comment by igorlukanin** [comment] 2024-08-29 15:02
Closing this one as resolved—please feel free to reopen if this is still an issue.

**Closed by igorlukanin** 2024-08-29 15:02 UTC
Labels: bug, api:sql
