### ISSUE TITLE
Problematic timeDImension filter generated by SQL API

### ISSUE THREAD

**Issue by igorcalabria** [cube-js/cube#6761] opened 2023-06-26 15:01 UTC
**Describe the bug**

When the time column is not the first element in the `WHERE` clause, the generated query contains a generic filter instead of the timeDimensions one. This is problematic because the query won't match preAggregations (https://cube.dev/docs/query-format#filters-operators-before-date)

**To Reproduce**
A query that filters on a dimension BEFORE the time dimension, like this 

```sql
EXPLAIN SELECT date_trunc('day', dt), sum(count)
FROM some_table
WHERE some_dimension = 'some_value' AND dt >= timestamp '2023-01-01' AND dt < timestamp '2023-02-01'
GROUP BY 1
```

generates the following query

```json
{
  "measures": [
    "some_table.count"
  ],
  "dimensions": [
    "some_table.dt"
  ],
  "timeDimensions": [
    {
      "dimension": "some_table.dt",
      "dateRange": [
        "2023-01-01",
        "2023-02-01"
      ]
    }
  ],
  "filters": [
    {
      "member": "some_table.some_dimension",
      "operator": "equals",
      "values": [
        "some_value"
      ]
    },
    {
      "member": "some_table.dt",
      "operator": "afterDate",
      "values": [
        "2023-01-01"
      ]
    },
    {
      "member": "some_table.dt",
      "operator": "beforeDate",
      "values": [
        "2023-02-01"
      ]
    }
  ]
}
```

If the `dt` filter is placed before `WHERE dt >= timestamp '2023-01-01' AND dt < timestamp '2023-02-01' AND some_dimension = 'some_value' `, the "correct" query is generated 

```sql
{
  "measures": [
    "some_table.count"
  ],
  "dimensions": [
    "some_table.dt"
  ],
  "timeDimensions": [
    {
      "dimension": "some_table.dt",
      "dateRange": [
        "2023-01-01",
        "2023-02-01"
      ]
    }
  ],
  "filters": [
    {
      "member": "some_table.some_dimension",
      "operator": "equals",
      "values": [
        "some_value"
      ]
    }
  ]
}
```

**Expected behavior**

I expected SQL API to place time filters in timeDimensions, regardless of the order in the `WHERE` clause

**Version:**
0.33.29

**Comment by paveltiunov** [comment] 2023-07-01 19:14
Duplicate of #6312

**Closed by paveltiunov** 2023-07-01 19:14 UTC
Labels: duplicate
