### ISSUE TITLE
rollup pre-aggregation alias bug

### ISSUE THREAD

**Issue by HsienWeiWang** [cube-js/cube#3539] opened 2021-10-13 15:45 UTC
**Describe the bug**
When using rollup type pre-aggregation, the alias name of the measure is the same before and after aggregation. So, when adding a filter on the measure, BigQuery is not able to distinguish in the "having" clause, causing `Aggregations of aggregations are not allowed` error.

**To Reproduce**
(I am using BigQuery, not sure whether any other DW has the same issue)
1. Define any measure in rollup type pre-aggregation
2. Select the measure in playground
3. Add any filter on that measure

**Expected behavior**
Maybe change the alias format in pre-aggregation

**Screenshots**
![image](https://user-images.githubusercontent.com/39364189/137165098-b993a178-42d0-4e94-93ab-ac7caa114b4a.png)

**Version:**
0.28.41

**Comment by rajatch80** [comment] 2024-04-08 09:27
@HsienWeiWang Any workaround you have found for this or have you just started using CubeStore?

**Comment by igorlukanin** [comment] 2024-04-08 10:45
@rajatch80 Does this reproduce for you as well? On which version of Cube (if you don't mind sharing)?

**Comment by igorlukanin** [comment] 2024-04-09 10:03
@rajatch80 If you don't want to use Cube Store, you can comment out the pre-aggregations in your data model and have Cube query your upstream data sources directly.

**Comment by igorlukanin** [comment] 2024-09-25 14:30
[Using external databases for pre-aggregations](https://github.com/cube-js/cube/blob/master/DEPRECATION.md#using-external-databases-for-pre-aggregations) has been deprecated. Please use Cube Store instead. Looks like this issue is not relevant anymore, so closing it.

**Closed by igorlukanin** 2024-09-25 14:30 UTC
Labels: bug, help wanted
