### ISSUE TITLE
Oracle 11.2 OFFSET FETCH gives error

### ISSUE THREAD

**Issue by niphadkarneha** [cube-js/cube#562] opened 2020-04-02 00:58 UTC
**Describe the bug**
I am using Oracle 11.2 database. When I run a query to fetch a list of account numbers for e.g.
```sql
SELECT
  account_number
FROM
  dummy.table FETCH NEXT 10000 ROWS ONLY
```
It throws an error of, "Error: ORA-00933: SQL command not properly ended". 
Adding a ' ; '  does not make any difference. The problem lies in the FETCH NEXT command which is auto-generated by Cubejs which is incompatible with Oracle 11.2.

[stackoverflow Issue](https://stackoverflow.com/questions/37836391/oracle-11g-offset-fetch-gives-error)

**Expected behavior**
Simple list of account numbers in a single column.

**Version:**
- Oracle version: 11.2
- node [node -v]  12.16.1
- npm [npm -v]   6.13.4 

**Additional context**
I'd be happy to provide any/all/more details.

**Comment by paveltiunov** [comment] 2020-04-02 18:56
@niphadkarneha Hey Neha! Thanks for posting this! I can confirm this syntax is available since version 12.

**Comment by malakiasz** [comment] 2020-06-01 03:27
Hello ,i have same problem with Oracle 11 g ( schema not generate correctly query for Oracle 11g)
U have A solutions for this ? 
Thanx

**Comment by igorlukanin** [comment] 2023-09-01 12:31
For the record, the solution to this should be similar to what is outlined in this comment: https://github.com/cube-js/cube/issues/191#issuecomment-524978540

**Comment by igorlukanin** [comment] 2024-09-24 16:34
I see that both Oracle 11, 12, and 18 are [not maintained anymore](https://en.wikipedia.org/wiki/Oracle_Database#Releases_and_versions). It means that this issue, that was specific for Oracle 11, is not relevant anymore. So, closing it now—please feel free to reopen if needed.

**Closed by igorlukanin** 2024-09-24 16:34 UTC
Labels: bug, help wanted, driver:oracle
