### ISSUE TITLE
What tools and indicators (metrics) does cube -js have for monitoring and tracking cube-js performance?

### ISSUE THREAD

**Issue by MuravevAV** [cube-js/cube#7732] opened 2024-02-07 09:05 UTC
What tools and indicators (metrics) does cube-js have to monitor and track the performance of cube-js? For example, we want to track how a Cube-js instance is using CPU and memory based on the number of user sessions, the number of active models, the number of concurrent database queries, etc. How to implement such a "Cube-JS performance monitor"? Are there any ready-made Cube-js metrics?

**Comment by paveltiunov** [comment] 2024-02-10 07:07
Duplicate of #2920

**Closed by paveltiunov** 2024-02-10 07:07 UTC
Labels: question
