### ISSUE TITLE
Float32 / Utf8 Error when creating custom column in metabase

### ISSUE THREAD

**Issue by jxperf** [cube-js/cube#6391] opened 2023-04-05 07:27 UTC
**Describe the bug**
Whenever you create a custom column in metabase which contains a division by any number this error will occur.
When you perform +, - or * operations, the expected output is delivered.

**To Reproduce**
1. Go to metabase
2. Create a question using the GUI builder
3. Create a custom column

**Expected behavior**
you would expect the values to be halved

**Screenshots**
![image](https://user-images.githubusercontent.com/108638581/230010226-4ac00ab1-0a17-4c2b-8ab4-4580bedc2207.png)
![image](https://user-images.githubusercontent.com/108638581/230010487-f9f0ab47-aba3-41a9-91f3-2747533a06f5.png)

**Minimally reproducible Cube Schema**

```javascript
cube(`common`, {
  sql: `
  select 1 as id, 'sydney' as place, 100 as total_sales
  UNION ALL
  select 2 as id, 'melbourne' as place, 200 as total_sales
  `,
  measures: {
    totalSales: {
      sql: `total_sales`,
      type: `sum`,
    },
  },
  dimensions: {
    place: {
      sql: `place`,
      type: `string`,
    },
  },
});
```

**Version:**
v0.32.16

**Additional context**
Datasource: Google Bigquery
Metabase Version: v0.45.0
This issue only seems to occur with google bigquery as the data source

**Comment by ovr** [comment] 2023-04-05 10:23
Hello @jxperf,

```
  dimensions: {
    place: {
      sql: `place`,
      type: `string`,
    },
  },
```

Why do you define numeric dimension as `string`? It looks like it should be `number` instead of `string`.


Thanks

**Comment by ovr** [comment] 2023-04-05 10:26
Hello @jxperf,

What result do you try to archive? It looks strange to do any kind of math expression between numbers and strings.

The same effect you will get with a real database.

```
test=# select 100 / 'sydney';
ERROR:  invalid input syntax for integer: "sydney"
LINE 1: select 100 / 'sydney';                     ^
```

Thanks

**Comment by jxperf** [comment] 2023-04-06 00:28
Hi @ovr, the result I am trying to achieve is to apply a division by the literal number 2 over the entire column. i.e. total sales should = `[50,100]`

this is the sql generated by metabase

```
SELECT "source"."place" AS "place", "source"."totalSales" AS "totalSales", "source"."__user" AS "__user", "source"."__cubeJoinField" AS "__cubeJoinField", "source"."sales by 2" AS "sales by 2"
FROM (SELECT "public"."Common"."place" AS "place", "public"."Common"."totalSales" AS "totalSales", "public"."Common"."__user" AS "__user", "public"."Common"."__cubeJoinField" AS "__cubeJoinField", (CAST("public"."Common"."totalSales" AS float) / CASE WHEN 2.0 = 0 THEN NULL ELSE 2.0 END) AS "sales by 2" FROM "public"."Common") "source"
LIMIT 1048575
```

**Comment by igorlukanin** [comment] 2024-10-08 23:24
@jxperf I have checked on Cube v0.36.7 (latest) with query pushdown on—it looks like this has been fixed:

<img width="1303" alt="Screenshot 2024-10-09 at 01 22 53" src="https://github.com/user-attachments/assets/5dc488f0-b5ea-42d0-80bd-c15eb7bfab25">

Closing this issue for now—please feel free to reopen if still reproduces for you.

**Closed by igorlukanin** 2024-10-08 23:24 UTC
Labels: bug, api:sql
