### ISSUE TITLE
AWS Athena v3: "Casting a Timestamp with Time Zone to Timestamp is not supported"

### ISSUE THREAD

**Issue by benhall-7** [cube-js/cube#5849] opened 2022-12-19 22:35 UTC
**Describe the bug**

AWS Athena v3 timestamps with TZ do not support casting into normal timestamps, resulting in an error if you run a query that uses granularity within a time dimension. The exact error message is in the title above.

**To Reproduce**

1. Use a cube with `athena` as the data source and at least one time dimension present
2. Run a query on this cube, with a time dimension + granularity

**Expected behavior**

The CubeJS produces compatible SQL for Athena v3 by avoiding this cast, and fetches the data.

**Minimally reproducible Cube Schema**

```javascript
cube(`Orders`, {
  sql: `
  select 1 as id, 100 as amount, 'new' status, '2022-12-13' day
  UNION ALL
  select 2 as id, 200 as amount, 'new' status, '2022-12-14' day
  UNION ALL
  select 3 as id, 300 as amount, 'processed' status, '2022-12-15' day
  UNION ALL
  select 4 as id, 500 as amount, 'processed' status, '2022-12-16' day
  UNION ALL
  select 5 as id, 600 as amount, 'shipped' status, '2022-12-17' day
  `,
  measures: {
    count: {
      type: `count`,
    },
    totalAmount: {
      sql: `amount`,
      type: `sum`,
    },
    toRemove: {
      type: `count`,
    },
  },
  dimensions: {
    status: {
      sql: `status`,
      type: `string`,
    },
    time: {
      sql: `from_iso8601_timestamp(day)`,
      type: `time`,
  },
});
```

**Version:**

CubeJS Athena driver v^0.29.21

Athena v3. The version of Athena itself is specified in AWS by default, and is able to be changed in the workgroup settings. See https://docs.aws.amazon.com/athena/latest/ug/engine-versions-changing.html

**Additional context**

We encountered this issue accidentally, when an engineer changed the version of Athena to version 3 in AWS. Prior to this change, it was not directly specified which version was used, which meant it was possible that it could switch with no warning. Athena v3 uses the Trino and Presto projects internally, but oddly, even though both of those projects support such casts, Athena v3 does not. Amazon published a changelog which specifically points out this limitation in the Breaking Changes section: https://docs.aws.amazon.com/athena/latest/ug/engine-versions-reference-0003.html.

The cast which actually raises the error should be found right here: https://github.com/cube-js/cube.js/blob/a8907df035cf53aeab3775990bd9e3ae891380e3/packages/cubejs-schema-compiler/src/adapter/PrestodbQuery.js#L51-L56

I can't verify this on my own, but it was suggested to me by another coworker that all that is necessary to fix this is remove the `CAST(X AS TIMESTAMP)` in the code above.

**Comment by igorlukanin** [comment] 2024-09-24 12:31
Hey @benhall-7 👋 

I have just tested this with the provided data model (just added the missing `}`) on the latest Cube (v0.36.2) and it looks like this issue has been already fixed. So, closing the issue for now—please feel free to reopen if it still reproduces for you.

Data model:
```js
cube(`Orders`, {
  sql: `
  select 1 as id, 100 as amount, 'new' status, '2022-12-13' day
  UNION ALL
  select 2 as id, 200 as amount, 'new' status, '2022-12-14' day
  UNION ALL
  select 3 as id, 300 as amount, 'processed' status, '2022-12-15' day
  UNION ALL
  select 4 as id, 500 as amount, 'processed' status, '2022-12-16' day
  UNION ALL
  select 5 as id, 600 as amount, 'shipped' status, '2022-12-17' day
  `,
  measures: {
    count: {
      type: `count`,
    },
    totalAmount: {
      sql: `amount`,
      type: `sum`,
    },
    toRemove: {
      type: `count`,
    },
  },
  dimensions: {
    status: {
      sql: `status`,
      type: `string`,
    },
    time: {
      sql: `from_iso8601_timestamp(day)`,
      type: `time`,
    }
  },
});
```

Query:
```json
{
  "limit": 5000,
  "timeDimensions": [
    {
      "dimension": "Orders.time",
      "granularity": "month"
    }
  ],
  "measures": [
    "Orders.count"
  ]
}
```

Generated SQL for Athena—note a sophisticated `CAST` for the time dimension:
```sql
SELECT
  date_trunc(
    'month',
    CAST(
      date_add(
        'minute',
        timezone_minute(from_iso8601_timestamp(day) AT TIME ZONE 'UTC'),
        date_add(
          'hour',
          timezone_hour(from_iso8601_timestamp(day) AT TIME ZONE 'UTC'),
          from_iso8601_timestamp(day)
        )
      ) AS TIMESTAMP
    )
  ) "orders__time_month",
  count(*) "orders__count"
FROM
  (
    select
      1 as id,
      100 as amount,
      'new' status,
      '2022-12-13' day
    UNION ALL
    select
      2 as id,
      200 as amount,
      'new' status,
      '2022-12-14' day
    UNION ALL
    select
      3 as id,
      300 as amount,
      'processed' status,
      '2022-12-15' day
    UNION ALL
    select
      4 as id,
      500 as amount,
      'processed' status,
      '2022-12-16' day
    UNION ALL
    select
      5 as id,
      600 as amount,
      'shipped' status,
      '2022-12-17' day
  ) AS "orders"
GROUP BY
  1
ORDER BY
  1 ASC
LIMIT
  5000
```

Cube Cloud query:
<img width="1392" alt="Screenshot 2024-09-24 at 14 31 00" src="https://github.com/user-attachments/assets/f00b0565-3fec-4f8b-8dd9-e236b8b12176">

Athena query log:
<img width="1392" alt="Screenshot 2024-09-24 at 14 30 47" src="https://github.com/user-attachments/assets/eef9028c-8640-4712-a292-362a81a3f58e">

**Closed by igorlukanin** 2024-09-24 12:31 UTC
Labels: bug, help wanted, driver:athena
