### ISSUE TITLE
Unable to connect Cube to an Oracle DB - neither from container, nor from Cube Cloud

### ISSUE THREAD

**Issue by manudc86** [cube-js/cube#5471] opened 2022-10-16 21:35 UTC
Hi! I am Manuel.

I am trying to create my first Cube deployment from scratch, connecting to an Oracle Database. I tried to connect to this database both from a locally hosted container that I've created following the steps in your docs (using docker-compose), and also I've tried to connect to this database from Cube Cloud. Either way, I get an error message, which is different for container and Cube Cloud

Error message when trying from container:

```
SyntaxCannot use import statement outside a module
/cube/node_modules/@cubejs-backend/oracle-driver/driver/OracleDriver.js:2
import {
^^^^^^


    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.lookupDriverClass (/cube/node_modules/@cubejs-backend/server-core/src/core/DriverResolvers.ts:35:18)
    at Object.dialectFactory (/cube/node_modules/@cubejs-backend/server-core/src/core/OptsHandler.ts:452:9)
    at CompilerApi.dialectClass (/cube/node_modules/@cubejs-backend/server-core/src/core/server.ts:461:26)
    at CompilerApi.getDialectClass (/cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:91:38)
    at /cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:77:37
    at async Promise.all (index 0)
    at CompilerApi.createQueryFactory (/cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:73:7)
    at CompilerApi.getCompilers (/cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:63:27)
    at CompilerApi.metaConfig (/cube/node_modules/@cubejs-backend/server-core/src/core/CompilerApi.js:179:13)
    at ApiGateway.meta (/cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:388:26)
    at /cube/node_modules/@cubejs-backend/api-gateway/src/gateway.ts:231:9
```

Error messaage when trying from Cube Cloud:

```
Runtime Error
Cube Cloud was unable to connect to the specified database.

The database returned the following error:

DPI-1047: Cannot locate a 64-bit Oracle Client library: "libclntsh.so: cannot open shared object file: No such file or directory". 
See https://oracle.github.io/odpi/doc/installation.html#linux for help Node-oracledb installation instructions: 
https://oracle.github.io/node-oracledb/INSTALL.html You must have 64-bit Oracle client libraries in LD_LIBRARY_PATH, or configured with ldconfig. 
If you do not have Oracle Database on this computer, then install the Instant Client Basic or Basic Light package from http://www.oracle.com/technetwork/topics/linuxx86-64soft-092277.html
```

Does anybody know what could be wrong, and how it could be fixed? Any more details, do not hesitate to ask.

Thank you for your help!!
Manuel Diz

**Comment by paveltiunov** [comment] 2022-10-24 03:40
@manudc86 Could you please check the latest docker image to see if it was fixed?

**Comment by MR-LI-ONEPIECE** [comment] 2023-03-01 03:47
This problem still exists in the latest version

**Comment by yohannfontaine** [comment] 2023-10-05 20:40
Hello, seems to be a duplicate of #3546
Installing the missing oracle client works for me.

Regards,
Yohann

**Comment by igorlukanin** [comment] 2024-10-09 00:05
Thanks @yohannfontaine 🙌 Closing in favor of https://github.com/cube-js/cube/issues/3546

**Closed by igorlukanin** 2024-10-09 00:05 UTC
Labels: bug, driver:oracle
