### ISSUE TITLE
Loading of an autogenerated schema file throws an error if the table has a column named 'columns'

### ISSUE THREAD

**Issue by nbanerje** [cube-js/cube#1572] opened 2020-12-10 21:24 UTC
**Describe the bug**
Loading of an autogenerated schema file throws an error if the table has a column named 'columns'

**To Reproduce**
Create a schema file with a dimension object called columns
```
dimensions: {
    columns: {
      sql: `columns`,
      type: `string`
    },
    ...
```

**Expected behavior**
Creating a schema from the UI should not create a schema file that causes an error

**Comment by ovr** [comment] 2020-12-14 12:38
It's caused by https://github.com/cube-js/cube.js/commit/d443585d0c9ba13942977540bf66f3a2579d6844

`columns` started to be a system field for references. There is only one solution for now, its change dimension name to anything else.

**Comment by igorlukanin** [comment] 2024-09-24 16:46
I've tried to reproduce this issue on the latest Cube (v0.36.2) and it looks like it has been resolved. Both YAML-based and JavaScript-based data models below work without issues:

```yaml
cubes:
  - name: columns_cube
    sql: SELECT 'foo' AS columns

    dimensions:
      - name: columns
        sql: columns
        type: string
```

```js
cube(`columns_cube_2`, {
  sql: `SELECT 'foo' AS columns`,

  dimensions: {
    columns: {
      sql: `columns`,
      type: `string`
    }
  }
})
```

<img width="1392" alt="Screenshot 2024-09-24 at 18 46 01" src="https://github.com/user-attachments/assets/a18f9206-08f7-4483-929d-193590efddf4">

<img width="1392" alt="Screenshot 2024-09-24 at 18 46 04" src="https://github.com/user-attachments/assets/d7390616-0128-4f7a-b462-4c67772f52e5">

With that, I think it's time to close the issue.

**Closed by igorlukanin** 2024-09-24 16:46 UTC
Labels: bug, help wanted, client:playground
